services:
  nestjs:
    build: .
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - .:/home/node/app
    command: sh -c "./entrypoint.sh"
    depends_on:
      nestjs-mysql:
        condition: service_healthy

  nestjs-mysql:
    image: mysql:8.0.30-debian
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./.docker/mysql:/docker-entrypoint-initdb.d
    healthcheck:
      test:
        ['CMD-SHELL', 'mysqladmin ping -h localhost -u root -proot --silent']
      interval: 30s
      retries: 10
      start_period: 60s
      timeout: 10s
