services:
  nestjs:
    build: .
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - .:/home/node/app
    command: sh -c "npm install && \
      npm run migrate:partner1 && \
      npm run migrate:partner2 && \
      npm run start partner1-fixture && \
      npm run start partner2-fixture && \
      npm run start:dev partner1 & \
      npm run start:dev partner2 & \
      wait"

  nestjs-mysql:
    image: mysql:8.0.30-debian
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./.docker/mysql:/docker-entrypoint-initdb.d
